version: '3.9'

volumes:
  webhooks_postgres_data:

services:
  # db access:
  ## docker exec -it examples_webhook-postgres_1 psql -U webhook-store
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: webhook-store
      POSTGRES_PASSWORD: IeRmL2Q12omWjMFy+HwmXL2R0lYufhQTZBEpW3+aJVw=
      POSTGRES_DB: webhook-store
    volumes:
      - webhooks_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging: &default-logging
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'

  # after first launch run migration
  # command:
  ## yarn prisma migrate deploy
  # example:
  ## docker exec -i examples-webhook-store-1 yarn prisma migrate deploy
  webhook-store:
    image: openwebhook/webhook-store:2.2.59
    environment:
      DATABASE_URL: postgresql://webhook-store:IeRmL2Q12omWjMFy+HwmXL2R0lYufhQTZBEpW3+aJVw=@postgres:5432/webhook-store?schema=public
    restart: unless-stopped
    depends_on:
      - postgres
    logging: *default-logging

  # post data:
  ## curl localhost:9000/8KCIPYs5FRsGvuzlIIa4sQ -d '{"a":1}'
  front:
    image: rhrn/dynamic-proxy:openresty-1.25
    restart: unless-stopped
    ports:
      - 9000:80
    logging: *default-logging
    command:
      - /bin/sh
      - -c
      - |
        cat << EOF > /etc/nginx/conf.d/default.conf
          server {

            listen 80;

            server_name _;

            resolver local=on;

            merge_slashes off;

            location /8KCIPYs5FRsGvuzlIIa4sQ {
              if (\$$request_method != POST) {
                return 403;
              }

              if (\$$request_uri ~* /(.*)) {
                proxy_pass http://webhook-store:3000;
              }
            }

            location / {
              return 403;
            }
          }
        EOF
        echo "----/etc/nginx/conf.d/default.conf-------"
        cat /etc/nginx/conf.d/default.conf
        echo "-----------------------------------------"
        /usr/local/openresty/bin/openresty -g "daemon off;"
    depends_on:
      - webhook-store
